# Generated by Django 5.2.17 on 2026-09-09 05:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Lesson",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=120, verbose_name="标题")),
                ("slug", models.SlugField(unique=True, verbose_name="标识")),
                ("summary", models.CharField(max_length=240, verbose_name="简介")),
                ("content", models.TextField(verbose_name="课程内容")),
                ("code", models.TextField(blank=True, verbose_name="代码示例")),
                (
                    "output",
                    models.CharField(
                        blank=True, max_length=240, verbose_name="运行结果"
                    ),
                ),
                (
                    "level",
                    models.CharField(
                        choices=[("入门", "入门"), ("基础", "基础"), ("进阶", "进阶")],
                        default="入门",
                        max_length=20,
                        verbose_name="难度",
                    ),
                ),
                (
                    "duration",
                    models.PositiveIntegerField(default=20, verbose_name="预计分钟"),
                ),
                ("order", models.PositiveIntegerField(default=1, verbose_name="排序")),
                (
                    "is_published",
                    models.BooleanField(default=True, verbose_name="已发布"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
            ],
            options={
                "verbose_name": "课程",
                "verbose_name_plural": "课程",
                "ordering": ["order", "id"],
            },
        ),
        migrations.CreateModel(
            name="QuizAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("score", models.PositiveIntegerField(verbose_name="得分")),
                ("total", models.PositiveIntegerField(verbose_name="总题数")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="提交时间"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "测验记录",
                "verbose_name_plural": "测验记录",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="QuizQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question", models.CharField(max_length=240, verbose_name="题目")),
                ("options", models.JSONField(verbose_name="选项")),
                ("answer", models.CharField(max_length=1, verbose_name="正确答案")),
                ("explanation", models.CharField(max_length=300, verbose_name="解析")),
                ("order", models.PositiveIntegerField(default=1, verbose_name="排序")),
                (
                    "lesson",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questions",
                        to="learning.lesson",
                    ),
                ),
            ],
            options={
                "verbose_name": "测验题目",
                "verbose_name_plural": "测验题目",
                "ordering": ["order", "id"],
            },
        ),
        migrations.CreateModel(
            name="Progress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "completed",
                    models.BooleanField(default=False, verbose_name="已完成"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "lesson",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="learning.lesson",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "学习进度",
                "verbose_name_plural": "学习进度",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "lesson"), name="unique_user_lesson_progress"
                    )
                ],
            },
        ),
    ]
